#!/bin/sh

offset=485  #a4hoehe-b6breite
offset2=130 #a4hoehe-2xb6breite
b6w=355

if [ -z "$2" ]; then 
  output=$(basename $1)
else
  output=$2
fi

bbox () {
  x=$1
  y=$2
  w=$3
  h=$4
}

bbox $(sed -n -e "s/^%%BoundingBox: //p" $1) 

new_bb="0 0 $h $((2*$w))"

psbook $1 | pstops "4:0L($h,0)+1L($h,$w)" | strippagesize "$new_bb" >v_$output
psbook $1 | pstops "4:2L($h,0)+3L($h,$w)" | strippagesize "$new_bb" >h_$output
