#!/bin/sh

W=596
H=842

if [ -z "$2" ]; then 
  output=cA4_$(basename $1)
else
  output=$2
fi

bbox () {
  x=$1
  y=$2
  w=$3
  h=$4
}

bbox $(sed -n -e "s/^%%BoundingBox: //p" $1) 

new_bb="0 0 $W $H"
xoff=$((($W-$w)/2))
yoff=$((($H-$h)/2))

pstops "1:0($xoff,$yoff)" $1 | strippagesize "$new_bb" >$output
