#!/bin/sh

if [ -z "$2" ]; then 
  output=$(basename $1)
else
  output=$2
fi

bbox () {
  x=$1
  y=$2
  w=$3
  h=$4
}

bbox $(sed -n -e "s/^%%BoundingBox: //p" $1) 

new_bb="0 0 $((2*$w)) $h"

psselect -p 2-,1 $1 | pstops "2:0+1($w,0)" | strippagesize "$new_bb" >demo_$output
