#!/bin/sh

xsize=420
ysize=596

if [ -z "$2" ]; then 
  output=$(basename $1)
else
  output=$2
fi

# Buggy because back side doesn't fit with front side
# psselect -o $1 | mypsbook -g2 | psnup -2 -s1 >v_$output
# psselect -e $1 | mypsbook -g2 | psnup -2 -s1 >h_$output

psselect -o $1 | mypsbook -g2 | pstops -pa4 "2:0L($ysize,0)+1L($ysize,$xsize)" >v_$output
psselect -e $1 | mypsbook -g2 | pstops -pa4 "2:0R(0,840)+1R(0,$xsize)" >h_$output
