#!/bin/sh

bbox="0 0 842 1191"  #A3

if [ -z "$2" ]; then 
  output=$(basename $1)
else
  output=$2
fi

v_posstring="3:0L(1w,0)+1L(1w,14cm)+2L(1w,28cm)"

h_posstring="3:2L(1w,0cm)+1L(1w,14cm)+0L(1w,28cm)"

pstops 2:0 $1 | mypsbook -g3 | pstops -pa3 "$v_posstring" | strippagesize "$bbox" a3 >v_$output
pstops 2:1 $1 | mypsbook -g3 | pstops -pa3 "$h_posstring" | strippagesize "$bbox" a3 >h_$output
