#!/bin/sh

if [ "$2" ]; then
  sed -e "/^%%BoundingBox:/a\\%%DocumentPaperSizes: $2" \
      -e "s/^%%BoundingBox: .*$/%%BoundingBox: $1/" \
      -e "/^%%DocumentPaperSizes:/d"
elif [ "$1" ]; then
  sed -e "s/^%%BoundingBox: .*$/%%BoundingBox: $1/" \
      -e "/^%%DocumentPaperSizes:/d"
else
  grep -v "BoundingBox\\|DocumentPaperSizes" 
fi
